#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="5.15.67proj1-ta1" --arg="/boot/vmlinuz-5.15.67proj1-ta1" /etc/kernel/postinst.d
exit 0
